image_root: '/workspace/pavan/multimodal/data/multimodal'
ann_root: 'annotation'
coco_gt_root: 'annotation/coco_gt'
train_path: '/workspace/pavan/multimodal/data/multimodal/train_topic_smallest.json'
val_path: '/workspace/pavan/multimodal/data/multimodal/iid_test_small_topic.json'
test_path: '/workspace/pavan/multimodal/data/multimodal/iid_test_small_topic.json'
dataset: 'WIDO'

# set pretrained as a file path or an url
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base.pth'

# size of vit model; base or large

vit: 'base'
batch_size_train: 64
batch_size_test: 64
vit_grad_ckpt: True
vit_ckpt_layer: 4
init_lr: 1e-5

# vit: 'large'
# batch_size_train: 16
# batch_size_test: 32
# vit_grad_ckpt: True
# vit_ckpt_layer: 12
# init_lr: 5e-6

image_size: 256
queue_size: 512
alpha: 0.4
k_test: 256
negative_all_rank: False

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 6

